### ISSUE TITLE
Bug in Glide backend parallelization

### ISSUE THREAD

**Issue by hshany** [MolecularAI/DockStream#2]
First, thanks for contributing this nice toolbox.

This is to report a bug in the following module:

https://github.com/MolecularAI/DockStream/blob/7bdfd4a67f5c938e3222db59387e5a95e8a59e56/dockstream/core/Schrodinger/Glide_docker.py#L404

`while` loop is used to process all sublists in batches. However, the number of processed sublists as recorded in `jobs_submitted` could be off because this variable is the cumulative sum of `len(tmp_output_dirs)`, which could be smaller than `len(cur_slice_sublists)` if any of the sublists has no valid molecules to write out.

The bug may cause some of the sublists get processed repeatedly, and in extreme cases may result in an infinite loop.

I didn't check if any other backend uses similar logic to parallelize the run and may suffer from the same problem.

**Comment by CMargreitter** [comment]
Hi,
Thanks for reporting this. This part of the code is far from ideal and is currently being reworked entirely (using a task status system, allowing resubmission etc.).

I believe the bug you've mentioned was introduced recently, and caused by this line in cases where an entire sublist failed to produce even one input structure:

https://github.com/MolecularAI/DockStream/blob/7bdfd4a67f5c938e3222db59387e5a95e8a59e56/dockstream/core/Schrodinger/Glide_docker.py#L383

Just pushed a hot-fix and also renamed "jobs_submitted" as this is a remnant from when there were individual molecules rather then sublists. Can you confirm that this solves the issue?

**Comment by hshany** [comment]
Yeah that did the trick. Thanks for the quick updating. 

Btw, it's nice to know that a more flexible task system is on the way. We did notice issues and to-be-improved aspects of the current parallelization scheme based on multiprocessing. For example, the initialization of new processes sometimes fail due to the "Too many files open" problem when we attempt to parallelize over a large number of cores, often cross nodes. Also, the way that subjobs are executed in batches mandates fast running jobs to wait for their slower peers. I bet the improvement that you are working on will address these issues.

Again, thanks for this nicely composed tool.

**Comment by CMargreitter** [comment]
Hi,

Cheers, thanks for reporting back. Are you sure the "Too many files open" problem still persists? I made a commit about a week ago that should have taken care of at least some of the issues there.

Yes, the points you mention should be properly addressed (maybe except for the asynchronous parallelization, which caused stability problems in the past). It will take some time until public release, though.
