### ISSUE TITLE
Raise LigandPreparationFailed error

### ISSUE THREAD

**Issue by fangffRS** [MolecularAI/DockStream#5]
For OpenEye Hybrid, it reported LigandPreparationFailed errors for both CORINA and OMEGA backend. One example is shown below:
`File "/DockStream/dockstream/core/OpenEyeHybrid/Omega_ligand_preparator.py", line 66, in __init__
    raise LigandPreparationFailed("Cannot initialize OMEGA backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize OMEGA backend - abort.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DockStream/docker.py", line 132, in <module>
    raise LigandPreparationFailed
dockstream.utils.dockstream_exceptions.LigandPreparationFailed`

Could you please help me with this problem? I tried both the provided receptor-ligand data files from DockStreamCommunity and my own dataset. Both reported same LigandPreparation error. Thank you in advance!

**Comment by GuoJeff** [comment]
Hi @fangffRS,

Thank you for your interest in DockStream. Just following up here from our email correspondence and in case this issue arises for other users. The following solution will be divided in two parts: 

(1) If OMEGA ligand embedding is not working due to the following error: `Cannot initialize OMEGA backend - abort`
(2) If Hybrid docking is not working due to the following error: `Cannot initialize OpenEye Hybrid docker, as OpenEye Hybrid backend is not available - abort.`

**For (1):** 
***The following line:*** `"prefix_execution": "module load omega"` initializes all OpenEye environment variables to run OMEGA.
 ***In the event this command does not work, try changing the above line to point to your OpenEye license file:***
`"prefix_execution": "export OE_LICENSE=<path to your oe_license file>"`

**For (2):** 
***The following line:*** `"prefix_execution": "module load oedocking"` initializes all OpenEye environment variables to run Hybrid. 
***In the event this command does not work, try changing the above line to:***
`"export CMAKE_PREFIX_PATH=<path to your oedocking installation directory>:<path to your omega installation directory>:<path to your oe_license directory>"`
